# Julia containers


### Array
 - list of mutable elements
 - can have multiple dimensions (e.g. 2d === matrix)
 - can be nested

In [1]:
# Simple array (a vector)
a = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [2]:
# 1-dimensional array with 2-elements (each of those is again a vector)
a = [[1,2,3],[4,5,6,7]] 

2-element Array{Array{Int64,1},1}:
 [1, 2, 3]   
 [4, 5, 6, 7]

In [3]:
# 2-dimensional array (a matrix with 2 columns) with three elements (scalars).
a = [[1,2,3] [4,5,6]] # [[elements of the first column] [elements of the second column] ...]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [4]:
# alternativly:
a = [1 4; 2 5; 3 6] # [first row; second row; ...]

3×2 Array{Int64,2}:
 1  4
 2  5
 3  6

In [5]:
# Linear algebra supported out-of the box
A = [[1,2,3] [4,5,6]]
B = [[1,2] [3,4] [5,6]] 
C = A * B

3×3 Array{Int64,2}:
  9  19  29
 12  26  40
 15  33  51

In [6]:
D = C'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
  9  12  15
 19  26  33
 29  40  51

In [7]:
# Solve linear system A X = C for X
X = A \ C

2×3 Array{Float64,2}:
 1.0  3.0  5.0
 2.0  4.0  6.0

In [9]:
# Determinant
# Need Standard Lib LinearAlgebra
using LinearAlgebra
E = [[1,2] [3,4]]
det(E)

-2.0

In [10]:
# Eigenvalues (characteristics roots or latent roots)
eigvals(E)

2-element Array{Float64,1}:
 -0.3722813232690143
  5.372281323269014 

In [11]:
# And if we don't remember the function to find the eigenvectors? Let's use the documentation

In [12]:
?eigenv

search: eigen! eigen Eigen GeneralizedEigen

Couldn't find eigenv
Perhaps you meant eigen, eigen!, Eigen, eigvecs, eigmax, eigmin or setenv


No documentation found.

Binding `eigenv` does not exist.


In [15]:
?eigvecs

search: eigvecs



```
eigvecs(A::SymTridiagonal[, eigvals]) -> Matrix
```

Return a matrix `M` whose columns are the eigenvectors of `A`. (The `k`th eigenvector can be obtained from the slice `M[:, k]`.)

If the optional vector of eigenvalues `eigvals` is specified, `eigvecs` returns the specific corresponding eigenvectors.

# Examples

```jldoctest
julia> A = SymTridiagonal([1.; 2.; 1.], [2.; 3.])
3×3 SymTridiagonal{Float64,Array{Float64,1}}:
 1.0  2.0   ⋅
 2.0  2.0  3.0
  ⋅   3.0  1.0

julia> eigvals(A)
3-element Array{Float64,1}:
 -2.1400549446402604
  1.0000000000000002
  5.140054944640259

julia> eigvecs(A)
3×3 Array{Float64,2}:
  0.418304  -0.83205      0.364299
 -0.656749  -7.39009e-16  0.754109
  0.627457   0.5547       0.546448

julia> eigvecs(A, [1.])
3×1 Array{Float64,2}:
  0.8320502943378438
  4.263514128092366e-17
 -0.5547001962252291
```

---

```
eigvecs(A; permute::Bool=true, scale::Bool=true, `sortby`) -> Matrix
```

Return a matrix `M` whose columns are the eigenvectors of `A`. (The `k`th eigenvector can be obtained from the slice `M[:, k]`.) The `permute`, `scale`, and `sortby` keywords are the same as for [`eigen`](@ref).

# Examples

```jldoctest
julia> eigvecs([1.0 0.0 0.0; 0.0 3.0 0.0; 0.0 0.0 18.0])
3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0
```

---

```
eigvecs(A, B) -> Matrix
```

Return a matrix `M` whose columns are the generalized eigenvectors of `A` and `B`. (The `k`th eigenvector can be obtained from the slice `M[:, k]`.)

# Examples

```jldoctest
julia> A = [1 0; 0 -1]
2×2 Array{Int64,2}:
 1   0
 0  -1

julia> B = [0 1; 1 0]
2×2 Array{Int64,2}:
 0  1
 1  0

julia> eigvecs(A, B)
2×2 Array{Complex{Float64},2}:
  0.0+1.0im   0.0-1.0im
 -1.0+0.0im  -1.0-0.0im
```


In [16]:
eigvecs(E)

2×2 Array{Float64,2}:
 -0.909377  -0.565767
  0.415974  -0.824565

### Tuples
list of immutable elements

In [17]:
a = (1,2,3)

(1, 2, 3)

### Sets
 - represent collections of unordered, unique values
 - support set operations

In [18]:
a = Set([1,2,2,3,4])

Set([4, 2, 3, 1])

In [19]:
b = Set([3,4,5,6])

Set([4, 3, 5, 6])

In [20]:
c = intersect(a,b)

Set([4, 3])

### Dictionaries
- store mappings from keys to values
- apparent random sorting

In [21]:
d = Dict('a'=>1, 'b'=>2, 'c'=>3)

Dict{Char,Int64} with 3 entries:
  'a' => 1
  'c' => 3
  'b' => 2

In [22]:
d['a']

1

In [23]:
for (k,v) in d
   println("$k is $v")
end

a is 1
c is 3
b is 2
